version: '3'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: cuytamvan
      POSTGRES_PASSWORD: cuytamvan
      POSTGRES_DB: test_chat
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  api:
    build:
      context: ./laravel
      dockerfile: Dockerfile
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=test_chat
      - DB_USERNAME=cuytamvan
      - DB_PASSWORD=cuytamvan
    volumes:
      - ./api:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - db

  vue:
    build:
      context: ./ui
      dockerfile: Dockerfile
    volumes:
      - ./vue:/app
      - /app/node_modules
    ports:
      - "5173:5173"

  socket:
    build:
      context: ./socket
      dockerfile: Dockerfile
    volumes:
      - ./socket:/app
      - /app/node_modules
    ports:
      - "5000:5000"

volumes:
  db_data: